name: meu_jardim_app

description: meu jardim.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_native_splash: ^2.3.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "6a994e"
  web: false
  fullscreen: false

  android_12:
    color: "6a994e"
 